### ISSUE TITLE
Photo Audit

### ISSUE THREAD

**Issue by danielqualitykitchen** [j0nscalet/QualityKitchen.API#83]
As a user I want to be able to swipe right on a task and then at a random frequency have a photo dialog pop up for the employee to take a picture of the task they claim to have finished to spec.  Once a task is swiped right to complete, on a random basis set a frequency of the stakeholders choosing, photo audits will pop-up to ensure the task is completed to spec. The photo audits will be delivered into it's own group in the Incident Center.

**Comment by danielqualitykitchen** [comment]
![1362367588524-2013-03-03 22 18 13](https://user-images.githubusercontent.com/26260226/27393298-88d14c1a-566e-11e7-86a6-8e9db8a5e669.png)

**Comment by danielqualitykitchen** [comment]
![1 photo audit timebomb](https://user-images.githubusercontent.com/26260226/27395084-33def0a8-5674-11e7-812d-26892effbd3f.png)
![photo audit timebomb](https://user-images.githubusercontent.com/26260226/27395098-3d3c18c4-5674-11e7-9549-dd789fe8669c.png)

**Comment by danielqualitykitchen** [comment]
Keep in mind I am just spitballing here.

Step 1: After employee as swiped right, at a random frequency the dialog to alert the user that a photo is required.  If possible I think a running clock is best to countdown in this screen as well to create a sense of urgency (restaurants love anything that implements a sense of urgency).

Step 2: Should the employee wish to swipe before taking a picture, it should be allowed or if the employee needs to sign out to allow a coworker to swipe real quick.  The time bomb should then have an icon which when clicked will take them back to the picture screen.

Step 3: Once a picture has been taken,  The photo should be in a seperate group in the incident center.  The date, time, task description, employee taking pic, shift and station should all be reported in the incident center

**Comment by j0nscalet** [comment]
@danielqualitykitchen Good use of an Epic here. At first glance I like where you're headed with this too. 

This kinda of thing should naturally transition us to a feature based team too. Here's how I picture it being different. Instead of attacking a huge backlog of issue like we're doing now, we'd create a released called 'Photo Audit'. The release would contain this one single 'Epic' where we'd break down the feature into smaller stories (issues), estimate those, and then you'd be able to clearly see when that's going to delivered. 

At the beginning of the release we'll go through a 'Design' phase which you've already started and we'll likely finish in the war room for Q3/Q4 planning in a few weeks. A natural flow through the software development lifecycle: design, build, test, deploy, maintain.

I'm hoping it completely laser focuses us on a feature and produces even better product for our users.
